const oportunidades = [
    {
        id: 1,
        titulo: "Cores e Contraste",
        subtitulo: "Concurso de fotografia",
        tipo: "concurso",
        area: "cultura",
        dataLimite: "2025-12-05",
        dataEvento: "2025-12-20",
        publico: "geral",
        descricao: "Participe de uma imersão na imagem. O concurso convida fotógrafos amadores e profissionais a explorar a história e a cultura... da vida urbana. Use suas lentes para capturar a beleza e o ritmo da sua cidade!",
        linkExterno: "#"
    },
    {
        id: 2,
        titulo: "Futuro da IA",
        subtitulo: "Palestra sobre Inteligência Artificial",
        tipo: "palestra",
        area: "tecnologia",
        dataLimite: "2025-11-10",
        dataEvento: "2025-11-17",
        publico: "estudante",
        descricao: "Explore as últimas tendências e o futuro da Inteligência Artificial em nossa palestra exclusiva. Palestrante renomado da área. Garanta sua vaga!",
        linkExterno: "#"
    },
    {
        id: 3,
        titulo: "Bolsas de Mestrado",
        subtitulo: "Edital de Fomento à Pesquisa",
        tipo: "edital",
        area: "educacao",
        dataLimite: "2025-11-20",
        dataEvento: "2025-11-26",
        publico: "profissional",
        descricao: "Editais abertos para bolsas de mestrado em diversas áreas. Oportunidade para aprofundar seus estudos e desenvolver pesquisas inovadoras. Consulte os requisitos.",
        linkExterno: "#"
    },
    {
        id: 4,
        titulo: "Expo Jovem Artista",
        subtitulo: "Concurso de Artes Visuais",
        tipo: "concurso",
        area: "artes",
        dataLimite: "2025-11-25",
        dataEvento: "2025-11-30",
        publico: "estudante",
        descricao: "Mostre seu talento artístico no concurso 'Expo Jovem Artista'! Aberto para estudantes com trabalhos em pintura, escultura, fotografia e mais. Detalhes no link.",
        linkExterno: "#"
    },
    {
        id: 5,
        titulo: "Estratégias de Marketing",
        subtitulo: "Palestra sobre Empreendedorismo",
        tipo: "palestra",
        area: "negocios",
        dataLimite: "2025-11-15",
        dataEvento: "2025-11-23",
        publico: "geral",
        descricao: "Aprenda as melhores estratégias de marketing para impulsionar seu negócio ou carreira. Palestra focada em resultados e inovação. Vagas limitadas!",
        linkExterno: "#"
    },
    {
        id: 6,
        titulo: "Roda de Ideias Culinárias",
        subtitulo: "Concurso de Culinária",
        tipo: "concurso",
        area: "culinaria", 
        dataLimite: "2025-11-30",
        dataEvento: "2025-12-07",
        publico: "geral",
        descricao: "Participe de uma experiência gastronômica completa: concorra a prêmios no Concurso de Culinária e, em seguida, troque receitas e dicas na Roda de Ideias...",
        linkExterno: "#"
    },
    {
        id: 7,
        titulo: "Hackathon de Frontend",
        subtitulo: "Tecnologia Front-End",
        tipo: "outros",
        area: "tecnologia",
        dataLimite: "2025-12-15",
        dataEvento: "2026-01-08",
        publico: "geral",
        descricao: "Participe do maior hackathon de frontend do ano! Desenvolva projetos incríveis e concorra a prêmios. Ideal para desenvolvedores que querem testar suas habilidades.",
        linkExterno: "#"
    },
    {
        id: 8,
        titulo: "Música e Dança",
        subtitulo: "Oficina de Ritmos Afro-Brasileiros",
        tipo: "outros",
        area: "cultura",
        dataLimite: "2025-12-05",
        dataEvento: "2025-12-20",
        publico: "geral",
        descricao: "Participe de uma imersão nos ritmos afro-brasileiros. A oficina une música e dança para explorar a história e a cultura...",
        linkExterno: "#"
    },
    {
        id: 9,
        titulo: "Ciência para Todos",
        subtitulo: "Palestra sobre Divulgação Científica",
        tipo: "palestra",
        area: "educacao",
        dataLimite: "2025-12-01",
        dataEvento: "2025-12-10",
        publico: "geral",
        descricao: "Descubra como a ciência pode ser acessível a todos. Palestra interativa sobre comunicação científica e o papel da divulgação na sociedade moderna.",
        linkExterno: "#"
    },
    {
        id: 10,
        titulo: "Startup Weekend",
        subtitulo: "Concurso de Inovação",
        tipo: "concurso",
        area: "negocios",
        dataLimite: "2025-12-10",
        dataEvento: "2025-12-18",
        publico: "profissional",
        descricao: "Transforme sua ideia em um negócio real em apenas 54 horas! Concorra a mentorias, investimentos e prêmios. Ideal para empreendedores iniciantes.",
        linkExterno: "#"
    },
    {
        id: 11,
        titulo: "Literatura Contemporânea",
        subtitulo: "Concurso de Contos",
        tipo: "concurso",
        area: "cultura",
        dataLimite: "2026-01-15",
        dataEvento: "2026-01-30",
        publico: "geral",
        descricao: "Mostre seu talento literário! Concurso aberto para contos inéditos de até 5 páginas. Prêmios incluem publicação e certificados. Tema livre.",
        linkExterno: "#"
    },
    {
        id: 12,
        titulo: "Sustentabilidade Urbana",
        subtitulo: "Edital de Projetos Ambientais",
        tipo: "edital",
        area: "meio-ambiente",
        dataLimite: "2025-12-20",
        dataEvento: "2026-01-10",
        publico: "profissional",
        descricao: "Edital para financiamento de projetos voltados à sustentabilidade urbana. Apoio financeiro e técnico para iniciativas inovadoras em gestão ambiental.",
        linkExterno: "#"
    },
    {
        id: 13,
        titulo: "Design Thinking",
        subtitulo: "Palestra sobre Inovação",
        tipo: "palestra",
        area: "tecnologia",
        dataLimite: "2025-11-28",
        dataEvento: "2025-12-05",
        publico: "estudante",
        descricao: "Aprenda metodologias ágeis e design thinking para resolver problemas complexos. Palestra prática com cases reais e exercícios em grupo.",
        linkExterno: "#"
    },
    {
        id: 14,
        titulo: "Festival de Cinema Independente",
        subtitulo: "Concurso de Curtas-Metragens",
        tipo: "concurso",
        area: "artes",
        dataLimite: "2026-01-05",
        dataEvento: "2026-01-20",
        publico: "geral",
        descricao: "Inscreva seu curta-metragem no festival! Categorias: ficção, documentário e animação. Premiação e exibição para os melhores trabalhos.",
        linkExterno: "#"
    },
    {
        id: 15,
        titulo: "Programação para Iniciantes",
        subtitulo: "Workshop de Python",
        tipo: "outros",
        area: "tecnologia",
        dataLimite: "2025-12-08",
        dataEvento: "2025-12-15",
        publico: "estudante",
        descricao: "Workshop gratuito de introdução à programação Python. Aprenda os fundamentos da linguagem mais versátil do mercado. Sem pré-requisitos necessários.",
        linkExterno: "#"
    },
    {
        id: 16,
        titulo: "Jogos Digitais e E-sports",
        subtitulo: "Palestra sobre Mercado de Games",
        tipo: "palestra",
        area: "tecnologia",
        dataLimite: "2025-12-12",
        dataEvento: "2025-12-19",
        publico: "geral",
        descricao: "Conheça as oportunidades profissionais no mercado de jogos digitais e e-sports. Palestrantes da indústria compartilham experiências e tendências.",
        linkExterno: "#"
    },
    {
        id: 17,
        titulo: "Teatro Experimental",
        subtitulo: "Edital de Peças Teatrais",
        tipo: "edital",
        area: "artes",
        dataLimite: "2026-01-10",
        dataEvento: "2026-01-25",
        publico: "estudante",
        descricao: "Edital para seleção de grupos de teatro experimental. Inscreva sua peça original e concorra a prêmios de até R$ 15.000,00 e temporadas em importantes teatros da cidade.",
        linkExterno: "#"
    },
    {
        id: 18,
        titulo: "Economia Criativa",
        subtitulo: "Edital de Apoio Cultural",
        tipo: "edital",
        area: "cultura",
        dataLimite: "2025-12-28",
        dataEvento: "2026-01-15",
        publico: "profissional",
        descricao: "Edital para projetos de economia criativa nas áreas de música, artes visuais, audiovisual e design. Recursos disponíveis para desenvolvimento e execução.",
        linkExterno: "#"
    },
    {
        id: 19,
        titulo: "Fotografia de Natureza",
        subtitulo: "Workshop de Fotografia",
        tipo: "outros",
        area: "cultura",
        dataLimite: "2025-12-03",
        dataEvento: "2025-12-11",
        publico: "geral",
        descricao: "Workshop prático de fotografia de natureza e paisagens. Aprenda técnicas de composição, iluminação natural e edição. Inclui saída de campo.",
        linkExterno: "#"
    },
    {
        id: 20,
        titulo: "Inclusão Digital",
        subtitulo: "Palestra sobre Acessibilidade",
        tipo: "palestra",
        area: "educacao",
        dataLimite: "2025-11-22",
        dataEvento: "2025-11-29",
        publico: "profissional",
        descricao: "Palestra sobre tecnologias assistivas e inclusão digital. Discuta barreiras e soluções para tornar a tecnologia acessível a todos. Certificado disponível.",
        linkExterno: "#"
    }
];